FROM node:22-alpine AS builder
WORKDIR /app

RUN corepack enable
RUN corepack prepare pnpm@latest --activate

COPY .gitignore .gitignore
COPY package.json package.json
COPY pnpm-lock.yaml pnpm-lock.yaml
RUN pnpm install --frozen-lockfile

COPY . .
RUN pnpm build
RUN pnpm build-storybook



FROM docker.io/httpd:2.4-alpine AS runner
RUN echo "$(date)" > /usr/local/apache2/htdocs/version.txt
COPY --from=builder --chown=www-data:www-data /app/storybook-static/ /usr/local/apache2/htdocs/
