version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    ports:
      - 3001:3000

  docs:
    build:
      context: .
      dockerfile: Dockerfile-docs
    ports:
      - 3002:3000
