[build]
command = "pnpm build-netlify:with-screenshots"
publish = "build-netlify/"

[build.environment]
PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD = "false"

[[plugins]]
package = "netlify-plugin-playwright-cache"
