name: Fix image
description: Fix an existing static or interactive image
title: "[Fix]: "
labels: ["fix image"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this report!
  - type: input
    id: link-to-paragraph
    attributes:
      label: Link to paragraph
      description: "Provide a url to the paragraph that the image is in. Tip the sections have a # sign where you can get the exact url of the section"
      placeholder: "https://dbalague.pages.ewi.tudelft.nl/openlabook/Chapter1/Inner_Product.html#inner-product"
    validations:
      required: false
  - type: input
    id: link-to-image
    attributes:
      label: Direct link to the applet
      description: "Provide the url of the applet/image that needs to be fixed."
      placeholder: "https://openla.ewi.tudelft.nl/applet/dot_product/inner_product_length"
    validations:
      required: false
  - type: dropdown
    id: applet-type
    attributes:
      label: What type of applet is this?
      description: Is this a static image, or an interactive applet?
      options:
        - Static image
        - Interactive applet 2D
        - Interactive applet 3D
        - Interactive slide show
    validations:
      required: true
  - type: textarea
    id: what-is-wrong
    attributes:
      label: What needs to change?
      description: Please provide a clear description with screenshots or sketches what need to change. Tip you can drag and drop images into this box.
      placeholder: The current image follows the equation x^2 + y^2 = 1, but it should follow x^2 + y^2 = 2
    validations:
      required: false
  - type: textarea
    id: linked-issues
    attributes:
      label: Does this issue relate or depend on other issues?
      description: "Add a list of issues that this issue depends on. Tip you can type # and then the issue number to get a list of issues."
      placeholder: "Depends on #1, #2. Relates to #3, #4."
    validations:
      required: false