name: Docker build & push image

on:
  push:
    branches: [ main ]
  workflow_dispatch:


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set lowercase repository owner environment variable (funky workaround because Docker is dumb)
        run: |
          echo "OWNER_LOWERCASE=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ env.OWNER_LOWERCASE }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push (web)
        # id: docker_build
        uses: docker/build-push-action@v3
        with:
          # context: "{{defaultContext}}:app"
          file: "Dockerfile-web"
          push: true
          tags: ghcr.io/${{ env.OWNER_LOWERCASE }}/interactive-visuals-web:latest

      - name: Build and push (docs)
        # id: docker_build
        uses: docker/build-push-action@v3
        with:
          # context: "{{defaultContext}}:app"
          file: "Dockerfile-docs"
          push: true
          tags: ghcr.io/${{ env.OWNER_LOWERCASE }}/interactive-visuals-docs:latest
